name: Azure Board Link Check

on: 
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  azure-link-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      - name: Check for Azure Board Link
        run: |
          PR_DESCRIPTION=$(gh pr view ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --json body -q .body)
          if [[ $PR_DESCRIPTION == *"dev.azure.com"* ]]; then
            echo "Azure Board link found in PR."
          else
            echo "No Azure Board link found in PR."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}